INSERT INTO `glpi_notificationtemplates` (`name`, `itemtype`, `date_mod`, `comment`, `css`, `date_creation`) VALUES ('RT Ajout Demandeur', 'Ticket', NULL, 'Created by the plugin RT', '', NULL);
INSERT INTO `glpi_notificationtemplatetranslations` (`notificationtemplates_id`, `language`, `subject`, `content_text`, `content_html`) VALUES (LAST_INSERT_ID(), 'fr_FR', '[GLPI] | Vos informations de connexion JCD', '', '
&#60;div class="es-wrapper-color" dir="ltr" lang="fr" style="background-color: #f6f6f6;"&#62;
&#60;table class="es-wrapper" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; padding: 0; margin: 0; width: 100%; height: 100%; background-repeat: repeat; background-position: center top; background-color: #f6f6f6;" role="none" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" valign="top"&#62;
&#60;table class="es-header" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; table-layout: fixed !important; width: 100%; background-color: transparent; background-repeat: repeat; background-position: center top;" role="none" cellspacing="0" cellpadding="0" align="center"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" align="center"&#62;
&#60;table class="es-header-body" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; background-color: transparent; width: 600px;" role="none" cellspacing="0" cellpadding="0" align="center" bgcolor="transparent"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="margin: 0; background-position: left top; padding: 20px;" align="left"&#62;
&#60;table class="es-left" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; float: left;" role="none" cellspacing="0" cellpadding="0" align="left"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td class="es-m-p20b" style="padding: 0; margin: 0; width: 270px;" align="left"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="presentation" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0; font-size: 0px;" align="center"&#62;&#60;img class="adapt-img" style="display: block; border: 0; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic;" src="https://fvjwbn.stripocdn.email/content/guids/CABINET_c5c51ff0181c45244ed7878853b49cd87c5602ebd7aea7b1e1b5fb0395aca382/images/logoeasisupportnew_c3i.png" alt="" width="270"&#62;&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;table class="es-right" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; float: right;" role="none" cellspacing="0" cellpadding="0" align="right"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0; width: 270px;" align="left"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="none" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0; display: none;" align="center"&#62; &#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;table class="es-content" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; table-layout: fixed !important; width: 100%;" role="none" cellspacing="0" cellpadding="0" align="center"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" align="center"&#62;
&#60;table class="es-content-body" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; background-color: #ffffff; width: 600px;" role="none" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="margin: 0; background-color: transparent; padding: 20px 20px 10px 20px;" align="left" bgcolor="transparent"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="none" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0; width: 560px;" align="center" valign="top"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; background-position: left top;" role="presentation" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td class="es-m-txt-l" style="padding: 0; margin: 0; padding-bottom: 10px;" align="center"&#62;
&#60;h2 style="margin: 0; line-height: 28.8px; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; font-size: 24px; font-style: normal; font-weight: bold; color: #040404;"&#62;Vos informations d’authentification&#60;/h2&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 20px; margin: 0;" align="center"&#62;
&#60;table style="border-collapse: collapse; border-spacing: 0px; height: 21.0938px;" role="presentation" border="0" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse; height: 21.0938px;"&#62;
&#60;td style="padding: 0px; margin: 0px; border-bottom: 1px solid rgb(204, 204, 204); background: none; width: 100%;"&#62; &#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td class="es-m-txt-l" style="padding: 0; margin: 0; padding-bottom: 10px;" align="left"&#62;
&#60;h2 style="margin: 0; line-height: 27.6px; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; font-size: 23px; font-style: normal; font-weight: bold; color: #040404;"&#62;&#60;strong&#62;Bonjour ##user.lastname##&#60;/strong&#62;,&#60;/h2&#62;
&#60;p style="margin: 0; -webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 21px; color: #040404; font-size: 14px;"&#62; &#60;/p&#62;
&#60;p style="margin: 0; -webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 21px; color: #040404; font-size: 14px;"&#62;Vous trouverez ci-dessous vos informations d\'identification pour accéder à vos tickets sur le site &#60;a style="-webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; text-decoration: underline; color: #040404; font-size: 14px;" href="https://servicedesk.easisupport.fr/" target="_new"&#62;ServiceDesk&#60;/a&#62;.&#60;/p&#62;
&#60;ul&#62;
&#60;li style="-webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 21px; margin-bottom: 15px; margin-left: 0; color: #040404; font-size: 14px;"&#62;&#60;strong&#62;Nom d\'utilisateur&#60;/strong&#62; : ##id.user##&#60;/li&#62;
&#60;li style="-webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 21px; margin-bottom: 15px; margin-left: 0; color: #040404; font-size: 14px;"&#62;&#60;strong&#62;Mot de passe&#60;/strong&#62; : ##user.password##&#60;/li&#62;
&#60;/ul&#62;
&#60;p style="margin: 0; -webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 21px; color: #040404; font-size: 14px;"&#62;Pour des raisons de sécurité, nous vous invitons à modifier votre mot de passe lors de votre première connexion.&#60;/p&#62;
&#60;p style="margin: 0; -webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 21px; color: #040404; font-size: 14px;"&#62; &#60;/p&#62;
&#60;p style="margin: 0; -webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 21px; color: #040404; font-size: 14px;"&#62;Nous restons à votre disposition pour toute assistance complémentaire.&#60;/p&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;table class="es-content" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; table-layout: fixed !important; width: 100%;" role="none" cellspacing="0" cellpadding="0" align="center"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" align="center"&#62;
&#60;table class="es-content-body" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; background-color: #ffffff; width: 600px;" role="none" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" align="left"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="none" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0; width: 600px;" align="center" valign="top"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="presentation" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" align="left"&#62;
&#60;p style="margin: 0; -webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 21px; color: #040404; font-size: 14px;"&#62;Cordialement,&#60;/p&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;table class="es-content" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; table-layout: fixed !important; width: 100%;" role="none" cellspacing="0" cellpadding="0" align="center"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" align="center"&#62;
&#60;table class="es-content-body" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; background-color: #ffffff; width: 600px;" role="none" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="margin: 0; padding: 20px;" align="left"&#62;
&#60;table class="es-left" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; float: left;" role="none" cellspacing="0" cellpadding="0" align="left"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td class="es-m-p20b" style="padding: 0; margin: 0; width: 180px;" align="left"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="presentation" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0; font-size: 0px;" align="left"&#62;&#60;img class="adapt-img" style="display: block; border: 0; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic;" src="https://fvjwbn.stripocdn.email/content/guids/CABINET_c5c51ff0181c45244ed7878853b49cd87c5602ebd7aea7b1e1b5fb0395aca382/images/logo_jcd_rZM.png" alt="" width="80"&#62;&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="none" cellspacing="0" cellpadding="0" align="right"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0; width: 360px;" align="left"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="presentation" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" align="left"&#62;
&#60;p style="margin: 0; -webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 16.8px; color: #040404; font-size: 14px;"&#62;&#60;br&#62;&#60;br&#62;&#60;strong&#62;L’équipe Easi Support&#60;/strong&#62;&#60;/p&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;table class="es-content" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; table-layout: fixed !important; width: 100%;" role="none" cellspacing="0" cellpadding="0" align="center"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" align="center"&#62;
&#60;table class="es-content-body" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px; background-color: #ffffff; width: 600px;" role="none" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="margin: 0; padding: 20px;" align="left"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="none" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0; width: 560px;" align="center" valign="top"&#62;
&#60;table style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; border-spacing: 0px;" role="presentation" width="100%" cellspacing="0" cellpadding="0"&#62;
&#60;tbody&#62;
&#60;tr style="border-collapse: collapse;"&#62;
&#60;td style="padding: 0; margin: 0;" align="left"&#62;
&#60;p style="margin: 0; -webkit-text-size-adjust: none; -ms-text-size-adjust: none; mso-line-height-rule: exactly; font-family: helvetica, "helvetica neue", arial, verdana, sans-serif; line-height: 18px; color: #040404; font-size: 12px;"&#62;&#60;br&#62;&#60;em&#62;Ce courrier électronique est envoyé automatiquement par le centre de service Easi Support.&#60;/em&#62;&#60;br&#62;&#60;br&#62;&#60;br&#62;Généré automatiquement par GLPI.&#60;/p&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/td&#62;
&#60;/tr&#62;
&#60;/tbody&#62;
&#60;/table&#62;
&#60;/div&#62;');